message = "Persistence detected on host"
category = "SampleCategory"
severity = "Debug"
campaign = "Interate over templates"
device_event_class = "SampleEventClass"
source_host_name = "SampleSourceHost"
source_host_id = "44444444-4444-4444-4444-444444444444"
destination_address = "SampleDestinationAddress"
destination_port = "8080"
file_hash = "abc123hash"
user = "sampleuser"

[properties.generation]
messages_per_interval = 5
interval = "Cycle"

[decoy]
name = "SampleDecoy"
type = "NetworkDevice"
id = "33333333-3333-3333-3333-333333333333"

[mitre_technique]
name = "SSH Authorized Keys"
id = "T1059.003"

[mitre_technique.tactic]
name = "Persistence"
id = "TA0003"
