#
# ### Continueous Integration (CI)
#
# Ensure that code successfully builds
#

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: vars/vars-all.yaml
- template: vars/vars-ci.yaml

steps:
- template: steps/git-checkout-self.yaml
- template: steps/use-dotnet-sdk.yaml
  parameters:
    version: '9.x'
- template: steps/build-solution.yaml
- template: steps/docker-build.yaml
