parameters:
- name: project
  type: string 
  default: $(Solution.MainProject)

variables:
  Project.MainDirectory: '$(Solution.DefaultWorkingDirectory)/${{ parameters.project }}'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build primary source'
  inputs:
    workingDirectory: $(Project.MainDirectory)
    command: 'build'